### ISSUE TITLE
failed tests after WCP chages

### ISSUE THREAD

**Issue by jefft0** [zb95/2016-ABAPlus#16]
After merging pull request #15 "WCP check fix", some tests fail when I run `python3 -m unittest`. Here is the output:

    FAIL: test_complex_WCP_no_violation_check1 (test.TestABAPlus)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jeff/work/2016-ABAPlus/test.py", line 320, in test_complex_WCP_no_violation_check1
        self.assertTrue(abap.check_WCP())
    AssertionError: False is not true

    ======================================================================
    FAIL: test_complex_WCP_no_violation_check2 (test.TestABAPlus)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jeff/work/2016-ABAPlus/test.py", line 365, in test_complex_WCP_no_violation_check2
        self.assertTrue(abap.check_WCP())
    AssertionError: False is not true

    ======================================================================
    FAIL: test_cycle_WCP_no_violation_check (test.TestABAPlus)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jeff/work/2016-ABAPlus/test.py", line 279, in test_cycle_WCP_no_violation_check
        self.assertTrue(abap.check_WCP())
    AssertionError: False is not true

    ======================================================================
    FAIL: test_simple_WCP_no_violation_check1 (test.TestABAPlus)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jeff/work/2016-ABAPlus/test.py", line 151, in test_simple_WCP_no_violation_check1
        self.assertTrue(abap.check_WCP())
    AssertionError: False is not true

    ======================================================================
    FAIL: test_simple_WCP_no_violation_check2 (test.TestABAPlus)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jeff/work/2016-ABAPlus/test.py", line 164, in test_simple_WCP_no_violation_check2
        self.assertTrue(abap.check_WCP())
    AssertionError: False is not true

    ======================================================================
    FAIL: test_simple_WCP_no_violation_check3 (test.TestABAPlus)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/jeff/work/2016-ABAPlus/test.py", line 178, in test_simple_WCP_no_violation_check3
        self.assertTrue(abap.check_WCP())
    AssertionError: False is not true

**Comment by zb95** [comment]
Since the tests are based on a stricter definition of WCP and Kristijonas made the WCP check more "lax",  they are no longer correct. . Kristijonas or I can add tests for the new WCP check when possible.

**Comment by jefft0** [comment]
Do you think that you or @kcyras will update the tests soon? If not, then I can submit a pull request to disable the tests until you update them.

**Comment by kcyras** [comment]
Re tests: I will do new ones, but really later, in a couple of weeks at the earliest, I imagine. So you could disable the old ones until I provide new ones. 

Re WCP fix: the fix itself had a small issue (just an incorrect exit from a for loop, really stupid on my side), so I've updated it, but haven't pushed on github, as I first wanted to test it live on the server, but the latter is down and I really don't have time to do it locally on my machine. So pending now.

**Comment by jefft0** [comment]
The WCP code is fixed and the tests now pass.
