### ISSUE TITLE
Missing files for TestABAPParser

### ISSUE THREAD

**Issue by jefft0** [zb95/2016-ABAPlus#6]
The unit test TestABAPParser needs files `test_generate_assumptions_from_file.pl` and `unit_tests_example6_input.pl`.  
https://github.com/zb95/2016-ABAPlus/blob/master/test.py#L799

But these files don't exist and the unit test gives an error. Do you plan to add the files? If not, I can do a pull request to comment out this test.

**Comment by zb95** [comment]
Thanks for noticing this!
I originally didn't intend to add test.py to the repository - it was included by accident.
But since you have already taken an interest in the test file, I will add these files.

**Comment by jefft0** [comment]
The added files work for me. Thanks!
